-- CreateEnum
CREATE TYPE "USER_ROLE" AS ENUM ('PROVIDER', 'CUSTOMER');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "USER_ROLE" NOT NULL DEFAULT 'CUSTOMER',
ALTER COLUMN "gender" SET DEFAULT 'OTHER';
